lab4t1/Models/Jogo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
namespace lab4t1.Models
{
    public class Jogo
    {
        [Key]
        public int Id { get; set; }
        [InverseProperty("Perfil")]

        [Required]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public string? Foto { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public double Preco { get; set; }

        [Display(Name = "Plataforma")]
        public int? PlataformaID { get; set; }

        [ForeignKey("PlataformaID")]
        [InverseProperty("Jogos")]
        public Plataforma? Plataforma { get; set; }

        [Display(Name = "Categoria")]
        public int?  CategoriaID { get; set; }

        [ForeignKey("CategoriaID")]
        [InverseProperty("Jogos")]
        public Categoria? Categoria { get; set; }

        [Display(Name = "Produtora")]
        public int? ProdutoraID { get; set; }

        [ForeignKey("ProdutoraID")]
        [InverseProperty("Jogos")]
        public Produtora? Produtora { get; set; }

        [Display(Name = "Funcionario")]
        public int? FuncionarioID { get; set; }
        [ForeignKey("FuncionarioID")]
        [InverseProperty("Jogos")]
        public Perfil? Perfil { get; set; }
    }

}

lab4t1/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab4t1.Data;
using lab4t1.Models;

namespace lab4t1.Controllers
{
    public class ComentariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComentariosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comentarios
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comentarios.Include(c => c.Jogo).Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comentarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Comentarios == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .Include(c => c.Jogo)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // GET: Comentarios/Create
        public IActionResult Create(int? id)
        {
            var jogo = _context.Jogos.SingleOrDefault(j => j.Id == id);
            ViewData["JogoId"]=jogo.Id;
            return View();
        }

        // POST: Comentarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Classificacao,Texto,UserID,JogoID")] Comentario comentario)
        {
            if (ModelState.IsValid)
            {
                var perfil = _context.Perfils.SingleOrDefault(m => m.UserName == User.Identity.Name);
                _context.Add(comentario);
                await _context.SaveChangesAsync();
                return RedirectToAction("Home","Index");
            }
            return View(comentario);
        }

        // GET: Comentarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Comentarios == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios.FindAsync(id);
            if (comentario == null)
            {
                return NotFound();
            }
            return View(comentario);
        }

        // POST: Comentarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Classificacao,Texto,UserID,JogoID")] Comentario comentario)
        {
            if (id != comentario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comentario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComentarioExists(comentario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["JogoID"] = new SelectList(_context.Jogos, "Id", "Description", comentario.JogoID);
            ViewData["UserID"] = new SelectList(_context.Perfils, "Id", "UserName", comentario.UserID);
            return View(comentario);
        }

        // GET: Comentarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Comentarios == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .Include(c => c.Jogo)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // POST: Comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Comentarios == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Comentario'  is null.");
            }
            var comentario = await _context.Comentarios.FindAsync(id);
            if (comentario != null)
            {
                _context.Comentarios.Remove(comentario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComentarioExists(int id)
        {
          return _context.Comentarios.Any(e => e.Id == id);
        }
    }
}

lab4t1/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab4t1.Data;
using lab4t1.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace lab4t1.Controllers
{
    public class JogosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostEnvironment _he;

        public JogosController(ApplicationDbContext context, IHostEnvironment he)
        {
            _context = context;
            _he = he;
        }

        // GET: Jogos

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Jogos.Include(j => j.Categoria).Include(j => j.Perfil).Include(j => j.Plataforma).Include(j => j.Produtora).ToListAsync();
            return View(await applicationDbContext);
        }

        // GET: Jogos/Details/5
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos
                .Include(j => j.Categoria)
                .Include(j => j.Perfil)
                .Include(j => j.Plataforma)
                .Include(j => j.Produtora)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jogo == null)
            {
                return NotFound();
            }

            return View(jogo);
        }

        // GET: Jogos/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "Id", "Name");
            ViewData["PlataformaID"] = new SelectList(_context.Plataformas, "Id", "Name");
            ViewData["ProdutoraID"] = new SelectList(_context.Produtoras, "Id", "Name");

            return View();
        }

        // POST: Jogos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Preco,Foto,PlataformaID,CategoriaID,ProdutoraID,FuncionarioID")] Jogo jogo, IFormCollection formData)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in formData.Files)
                {
                    jogo.Foto = file.FileName;
                    string dir = Path.Combine(
                        _he.ContentRootPath, "wwwroot/Jogos/", jogo.Name
                        );

                    if (!Directory.Exists(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                    string des = Path.Combine(dir, Path.GetFileName(file.FileName));
                    FileStream fs = new FileStream(des, FileMode.Create, FileAccess.Write);
                    file.CopyTo(fs);
                    fs.Close();

                }
                var perfil = await _context.Perfils.FirstOrDefaultAsync(m => m.UserName == User.Identity.Name);
                jogo.FuncionarioID = perfil.Id;
                _context.Add(jogo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "Id", "Name", jogo.CategoriaID);
            ViewData["PlataformaID"] = new SelectList(_context.Plataformas, "Id", "Name", jogo.PlataformaID);
            ViewData["ProdutoraID"] = new SelectList(_context.Produtoras, "Id", "Name", jogo.ProdutoraID);
            return View(jogo);
        }

        // GET: Jogos/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos.FindAsync(id);
            if (jogo == null)
            {
                return NotFound();
            }
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "Id", "Name", jogo.CategoriaID);
            ViewData["PlataformaID"] = new SelectList(_context.Plataformas, "Id", "Name", jogo.PlataformaID);
            ViewData["ProdutoraID"] = new SelectList(_context.Produtoras, "Id", "Name", jogo.ProdutoraID);
            return View(jogo);
        }

        // POST: Jogos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Preco,PlataformaID,CategoriaID,ProdutoraID,FuncionarioID")] Jogo jogo)
        {
            
            if (id != jogo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var perfil = await _context.Perfils.FirstOrDefaultAsync(m => m.UserName == User.Identity.Name);
                    jogo.FuncionarioID = perfil.Id;
                    _context.Update(jogo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogoExists(jogo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "Id", "Name", jogo.CategoriaID);
            ViewData["PlataformaID"] = new SelectList(_context.Plataformas, "Id", "Name", jogo.PlataformaID);
            ViewData["ProdutoraID"] = new SelectList(_context.Produtoras, "Id", "Name", jogo.ProdutoraID);
            return View(jogo);
        }

        // GET: Jogos/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos
                .Include(j => j.Categoria)
                .Include(j => j.Perfil)
                .Include(j => j.Plataforma)
                .Include(j => j.Produtora)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jogo == null)
            {
                return NotFound();
            }

            return View(jogo);
        }

        // POST: Jogos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jogos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Jogos'  is null.");
            }
            var jogo = await _context.Jogos.FindAsync(id);
            if (jogo != null)
            {
                _context.Jogos.Remove(jogo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JogoExists(int id)
        {
          return _context.Jogos.Any(e => e.Id == id);
        }

        public async  Task<IActionResult> JogoComprado()
        {
            return View();
        }
    }
}

lab4t1/Views/Jogos/Create.cshtml
@model lab4t1.Models.Jogo

@{
    ViewData["Title"] = "Create";
}
<body style="background-color:#212529">
    <h1 class="text-white" style="text-align:center">Adicionar Jogo</h1>

<h1 class="text-white" style ="text-align:center">Jogo</h1>
<hr />
<div class="row">
        <div class="col-md-4 text-white">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlataformaID" class="control-label"></label>
                <select asp-for="PlataformaID" class ="form-control" asp-items="ViewBag.PlataformaID"></select>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaID" class="control-label"></label>
                <select asp-for="CategoriaID" class ="form-control" asp-items="ViewBag.CategoriaID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProdutoraID" class="control-label"></label>
                <select asp-for="ProdutoraID" class ="form-control" asp-items="ViewBag.ProdutoraID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for ="Foto" type="file" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar Jogo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab4t1/Views/Jogos/Delete.cshtml
@model lab4t1.Models.Jogo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jogo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plataforma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plataforma.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produtora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produtora.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Perfil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Perfil.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

lab4t1/Views/Jogos/Details.cshtml
@model lab4t1.Models.Jogo
@{
    ViewData["Title"] = "Details";
}

<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css%22%3E">
        <link href="~/css/details.css" rel="stylesheet" />
</head>
<body style="background-color:#212529">
    <div class="DerJeito">
        <div class="container-fluid my-5">
            <div class="row  ">
                <div class="card mb-3 CartaoFixe">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="/images/football Manager.png" class="img-fluid" alt="Imagem do Jogo">
                        </div>
                        <div class="col-md-8 px-4">
                            <div class="card-body" id=" ColunaInfo">
                                           <h1 class="text-white mb-3 h1-maior">@Html.DisplayFor(model => model.Name)</h1>
                            <div class="d-grid gap-2 col-6">
                                    <button type="button" class="btn btn-warning" disabled>Preço:  @Model.Preco €</button>
                                    <button type="button" class="btn btn-warning" disabled>Plataforma:  @Html.DisplayFor(model => model.Plataforma.Name)</button>
                            <button type="button" class="btn btn-warning" disabled>Categoria: @Html.DisplayFor(model => model.Categoria.Name)</button>
                            <button type="button" class="btn btn-warning" disabled>Produtora:  @Html.DisplayFor(model => model.Produtora.Name)</button>
                                    <a class="btn btn-light mt-auto" href="#">Comprar</a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h2 class="text-white">Descrição:</h2>
                    <p class="text-white">@Model.Description</p>
                    <hr class="text-white" />
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a asp-controller="Comentarios" asp-action="Create" class="btn btn-primary text-white" asp-route-id="@Model?.Id">Comentar</a>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" class="btn btn-primary text-white" asp-route-id="@Model?.Id">Editar</a>
                    }
                    <a asp-controller="Home" asp-action="Index" class="btn btn-secondary text-white">Voltar à página Inicial</a>
                </div>
            </div>


        </div>
    </div>
</body>


</html>

lab4t1/Views/Jogos/Edit.cshtml
@model lab4t1.Models.Jogo

@{
    ViewData["Title"] = "Edit";
}
<body style="background-color:#212529">
    <h1 class="text-white" style="text-align:center">Editar Jogo</h1>

<h4>Jogo</h4>
<hr />
    <div class="row text-white">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlataformaID" class="control-label"></label>
                <select asp-for="PlataformaID" class="form-control" asp-items="ViewBag.PlataformaID"></select>
                <span asp-validation-for="PlataformaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaID" class="control-label"></label>
                <select asp-for="CategoriaID" class="form-control" asp-items="ViewBag.CategoriaID"></select>
                <span asp-validation-for="CategoriaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProdutoraID" class="control-label"></label>
                <select asp-for="ProdutoraID" class="form-control" asp-items="ViewBag.ProdutoraID"></select>
                <span asp-validation-for="ProdutoraID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="text-white">Voltar à lista</a>
</div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab4t1/Views/Jogos/Index.cshtml
@model IEnumerable<lab4t1.Models.Jogo>

@{
    ViewData["Title"] = "Index";
}
<body style="background-color:#212529">
<h1 class="text-white" style ="text-align:center">Lista de Jogos</h1>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center text-white">
                        <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Preco)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Plataforma)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Categoria)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Produtora)
                    </th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody class="text-white">
                @foreach (var item in Model)
                {
                        <tr class="text-center">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Preco)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Plataforma.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Produtora.Name)
                        </td>
                        <td>
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Editar </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Detalhes </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Apagar </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
</body>
@await Html.PartialAsync("_CreateItem", "Jogos")

lab4t1/Views/Jogos/JogoComprado.cshtml
@model lab4t1.Models.Jogo

@{
    ViewData["Title"] = "JogoComprado";
}

<body style="background-color:#212529">
    <div class="text-center">
        <h1 class="text-success">JOGO COMPRADO COM SUCESSO</h1>
    </div>
</body>